export { default as Header } from './header/Header';
export { default as Categories } from './categories/Categories';
export { default as Sort } from './sort/Sort';
export { default as PizzaBlock } from './pizzaBlock/PizzaBlock';
export { default as CartItem } from './cartItem/CartItem';
export { default as PizzaLoadingBlock } from './pizzaLoadingBlock/PizzaLoadingBlock';
export { default as NotFoundPage } from './notFoundPage/NotFoundPage';
export { default as Search } from './search/Search';
export { default as Pagination } from './pagination/Pagination';
